create table public.loyalty_cards (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique_id text not null unique,
  first_name text,
  last_name text,
  phone_number text unique,
  email text unique,
  points integer default 0,
  tier text default 'Member',
  is_activated boolean default false not null
);

alter table public.loyalty_cards enable row level security;

create policy "Enable public read access" on public.loyalty_cards
  for select using (true);

create policy "Enable card activation updates" on public.loyalty_cards
  for update using (is_activated = false)
  with check (true);

-- Sample activated cards
insert into public.loyalty_cards (unique_id, first_name, last_name, phone_number, email, points, tier, is_activated)
values
  ('882910', 'Juan', 'Dela Cruz', '09171234567', 'juan@email.com', 1250, 'Gold', true),
  ('102030', 'Maria', 'Santos', '09171234568', 'maria@email.com', 450, 'Silver', true),
  ('555555', 'Cookie', 'Monster', '09171234569', 'cookie@email.com', 9999, 'Platinum', true);

-- Sample unactivated cards for admins to distribute
insert into public.loyalty_cards (unique_id)
values
  ('111111'),
  ('222222'),
  ('333333');

-- Function to atomically add points to an activated card.
-- This function runs with the permissions of the definer, bypassing RLS for this specific action.
create or replace function public.add_points(card_id text, points_to_add integer)
returns void
language plpgsql
security definer
as $$
begin
  update public.loyalty_cards
  set points = points + points_to_add
  where unique_id = card_id and is_activated = true;
end;
$$;

-- Grant execute permission to the anon role so it can be called from the frontend
grant execute on function public.add_points(text, integer) to anon;

-- Function to atomically deduct points from an activated card.
-- This function runs with the permissions of the definer, bypassing RLS.
create or replace function public.deduct_points(card_id text, points_to_deduct integer)
returns void
language plpgsql
security definer
as $$
begin
  update public.loyalty_cards
  set points = points - points_to_deduct
  where unique_id = card_id and is_activated = true and points >= points_to_deduct;
end;
$$;

-- Grant execute permission to the anon role so it can be called from the frontend
grant execute on function public.deduct_points(text, integer) to anon;