create table public.loyalty_cards (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique_id text not null unique,
  first_name text,
  last_name text,
  phone_number text unique,
  email text unique,
  points integer default 0,
  tier text default 'Member',
  is_activated boolean default false not null,
  expires_at timestamp with time zone
);

alter table public.loyalty_cards enable row level security;

create policy "Enable public read access" on public.loyalty_cards
  for select using (true);

create policy "Enable card activation updates" on public.loyalty_cards
  for update using (is_activated = false)
  with check (true);

-- Sample activated cards
insert into public.loyalty_cards (unique_id, first_name, last_name, phone_number, email, points, tier, is_activated, expires_at)
values
  ('882910', 'Juan', 'Dela Cruz', '09171234567', 'juan@email.com', 1250, 'Gold', true, '2028-03-31'),
  ('102030', 'Maria', 'Santos', '09171234568', 'maria@email.com', 450, 'Silver', true, '2028-03-31'),
  ('555555', 'Cookie', 'Monster', '09171234569', 'cookie@email.com', 9999, 'Platinum', true, '2028-03-31');

-- Sample unactivated cards for admins to distribute
insert into public.loyalty_cards (unique_id, expires_at)
values
  ('111111', null),
  ('222222', null),
  ('333333', null),
  ('482193', '2028-03-31 23:59:00'),
  ('705614', '2028-03-31 23:59:00'),
  ('139482', '2028-03-31 23:59:00'),
  ('864205', '2028-03-31 23:59:00'),
  ('517938', '2028-03-31 23:59:00'),
  ('290761', '2028-03-31 23:59:00'),
  ('643519', '2028-03-31 23:59:00'),
  ('781024', '2028-03-31 23:59:00'),
  ('356918', '2028-03-31 23:59:00'),
  ('924607', '2028-03-31 23:59:00'),
  ('118593', '2028-03-31 23:59:00'),
  ('672405', '2028-03-31 23:59:00'),
  ('903176', '2028-03-31 23:59:00'),
  ('245890', '2028-03-31 23:59:00'),
  ('817362', '2028-03-31 23:59:00'),
  ('594721', '2028-03-31 23:59:00'),
  ('730846', '2028-03-31 23:59:00'),
  ('169254', '2028-03-31 23:59:00'),
  ('428907', '2028-03-31 23:59:00'),
  ('601735', '2028-03-31 23:59:00'),
  ('852164', '2028-03-31 23:59:00'),
  ('314780', '2028-03-31 23:59:00'),
  ('907452', '2028-03-31 23:59:00'),
  ('568139', '2028-03-31 23:59:00'),
  ('742601', '2028-03-31 23:59:00'),
  ('190374', '2028-03-31 23:59:00'),
  ('836295', '2028-03-31 23:59:00'),
  ('475018', '2028-03-31 23:59:00'),
  ('621943', '2028-03-31 23:59:00'),
  ('754206', '2028-03-31 23:59:00'),
  ('318579', '2028-03-31 23:59:00'),
  ('902641', '2028-03-31 23:59:00'),
  ('147803', '2028-03-31 23:59:00'),
  ('685214', '2028-03-31 23:59:00'),
  ('239570', '2028-03-31 23:59:00'),
  ('861493', '2028-03-31 23:59:00'),
  ('504728', '2028-03-31 23:59:00'),
  ('973160', '2028-03-31 23:59:00'),
  ('426815', '2028-03-31 23:59:00'),
  ('715902', '2028-03-31 23:59:00'),
  ('348761', '2028-03-31 23:59:00'),
  ('629054', '2028-03-31 23:59:00'),
  ('804237', '2028-03-31 23:59:00'),
  ('152986', '2028-03-31 23:59:00'),
  ('697318', '2028-03-31 23:59:00'),
  ('540672', '2028-03-31 23:59:00'),
  ('283419', '2028-03-31 23:59:00'),
  ('760145', '2028-03-31 23:59:00'),
  ('918263', '2028-03-31 23:59:00'),
  ('374508', '2028-03-31 23:59:00');

-- Function to atomically add points to an activated card.
-- This function runs with the permissions of the definer, bypassing RLS for this specific action.
create or replace function public.add_points(card_id text, points_to_add integer)
returns void
language plpgsql
security definer
as $$
begin
  update public.loyalty_cards
  set points = points + points_to_add
  where unique_id = card_id and is_activated = true;
end;
$$;

-- Grant execute permission to the anon role so it can be called from the frontend
grant execute on function public.add_points(text, integer) to anon;

-- Function to atomically deduct points from an activated card.
-- This function runs with the permissions of the definer, bypassing RLS.
create or replace function public.deduct_points(card_id text, points_to_deduct integer)
returns void
language plpgsql
security definer
as $$
begin
  update public.loyalty_cards
  set points = points - points_to_deduct
  where unique_id = card_id and is_activated = true and points >= points_to_deduct;
end;
$$;

-- Grant execute permission to the anon role so it can be called from the frontend
grant execute on function public.deduct_points(text, integer) to anon;
